### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [Edwin-F/AppSplurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by Edwin-F** [comment]
Thanks for the feedback. I added the "mobile meta tag" in the <head> tags and pushed the app on github.

**Comment by Mikeysax** [comment]
Hey Edwin, nice job adding the tag :+1:
